//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAnnotation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Emp
    {
        [Display(Name ="Employee Id")]
        public int eid { get; set; }
        
        
        [Display(Name = "Employee Name")]
        [Required(ErrorMessage ="Name can not empty")]
        public string ename { get; set; }
        
        
        [Display(Name = "City")]
        [Required(ErrorMessage = "Please enter city name")]
        public string city { get; set; }
        
        
        [Display(Name = "Department Code")]
        public Nullable<int> dcode { get; set; }

        
        public virtual Department Department { get; set; }

    }
}
